% Convenience script for running a single test.
addpaths;
test_result = runtest(...
    'ame',struct(),...
    'objectworld',struct('feature_type','grid'),...
    struct(...
        'training_sample_lengths',32,...
        'training_samples',16,...
        'test_samples',32,...
        'example_restarts',1,...
        'test_restarts',1,...
        'example_optimal',0,...
        'example_recompute_optimal',0,...
        'test_optimal',0,...
        'cells_state',20,...
        'cells_action',5,...
        'verbosity',4));

% Visualize solution.
visualize(test_result);
