% Plot the shape of a car.
function [xv,yv] = highwaycarplot(pos,theta,car_width,car_height)

xv = [pos(1) - car_width*cos(theta) - car_height*sin(theta),...
      pos(1) - car_width*cos(theta) + car_height*0.8*sin(theta),...
      pos(1) - car_width*0.6*cos(theta) + car_height*sin(theta),...
      pos(1) + car_width*0.6*cos(theta) + car_height*sin(theta),...
      pos(1) + car_width*cos(theta) + car_height*0.8*sin(theta),...
      pos(1) + car_width*cos(theta) - car_height*sin(theta),...
      pos(1) - car_width*cos(theta) - car_height*sin(theta),...
      pos(1) - car_width*cos(theta) + car_height*0.8*sin(theta)];
yv = [pos(2) + car_width*sin(theta) - car_height*cos(theta),...
      pos(2) + car_width*sin(theta) + car_height*0.8*cos(theta),...
      pos(2) + car_width*0.6*sin(theta) + car_height*cos(theta),...
      pos(2) - car_width*0.6*sin(theta) + car_height*cos(theta),...
      pos(2) - car_width*sin(theta) + car_height*0.8*cos(theta),...
      pos(2) - car_width*sin(theta) - car_height*cos(theta),...
      pos(2) + car_width*sin(theta) - car_height*cos(theta),...
      pos(2) + car_width*sin(theta) + car_height*0.8*cos(theta)];
